config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/health', to: proc { [200, {}, ['success']] }

  match 'catalog_entry', to: 'catalog_entry#index', via: [:get, :post]

  match 'api/collections', to: 'canons#index', via: [:get, :post]
  match '/api/collections/:uuid/resources', to: 'works#index', via: [:get, :post]
  match '/api/resources/:uuid/sections', 
        to: 'juans#list_for_asia_network', 
        via: [:get, :post]
  match '/api/sections/:uuid/content_units', 
        to: 'juans#content_for_asia_network', 
        via: [:get, :post]
  match '/api/sections/:uuid', to: 'juans#show_for_asia_network', via: [:get, :post]

  match 'category/:category', to: 'juans#index', via: [:get, :post]
  match 'chinese_tools/sc2tc', via: [:get, :post]
  get 'download/:id', to: 'download#index', id: /.+/
  
  match 'export/all_creators2', via: [:get, :post]
  match 'export/all_creators', via: [:get, :post]
  match 'export/all_works', via: [:get, :post]
  match 'export/check_list', via: [:get, :post]
  match 'export/creator_strokes', via: [:get, :post]
  match 'export/creator_strokes_works', via: [:get, :post]
  match 'export/dynasty_works', via: [:get, :post]
  match 'export/dynasty', via: [:get, :post]
  match 'export/scope_selector_by_category', via: [:get, :post]
  match 'export/scope_selector_by_vol', via: [:get, :post]

  match 'juans/goto', via: [:get, :post]
  match 'juans', to: 'juans#index', via: [:get, :post]

  match 'lines', to: 'lines#index', via: [:get, :post]
  
  match 'report', to: 'report#index', as: :reports, via: [:get, :post]
  get   'report/access'
  get   'report/daily',   to: 'report#daily',   as: :report_daily
  match 'report/url',     to: 'report#url',     as: :report_url,     via: [:get, :post]
  match 'report/referer', to: 'report#referer', as: :report_referer, via: [:get, :post]
  match   'report/total',   to: 'report#total', via: [:get, :post]

  match 'search/all_in_one',      to: 'search#all_in_one', via: [:get, :post]
  match 'search/extended',        to: 'search#extended',   via: [:get, :post]
  match 'search/facet/:facet_by', to: 'search#facet',      via: [:get, :post]
  match 'search/kwic',            to: 'kwic3#juan',        via: [:get, :post]
  match 'search/notes',           to: 'search#notes',      via: [:get, :post]
  match 'search/sc',              to: 'search#sc',         via: [:get, :post]
  match 'search/similar',         to: 'search#similar',    via: [:get, :post]
  match 'search/synonym',         to: 'search#synonym',    via: [:get, :post]
  match 'search/title',           to: 'search#title',      via: [:get, :post]
  match 'search/toc',             to: 'toc_node#index',    via: [:get, :post]
  match 'search/variants',        to: 'search#variants',   via: [:get, :post]
  match 'search',                 to: 'search#index',      via: [:get, :post]

  get 'static_pages/chinese_tools'
  get 'static_pages/catalog_index'
  get 'static_pages/catalog'
  get 'static_pages/callback'
  get 'static_pages/category'
  get 'static_pages/common_parameters'
  get 'static_pages/creators'
  get 'static_pages/download_docusky'
  get 'static_pages/download_ebooks'
  get 'static_pages/download_footnotes'
  get 'static_pages/download_html'
  get 'static_pages/download_text'
  get 'static_pages/download'
  get 'static_pages/export'
  get 'static_pages/get_html'
  get 'static_pages/goto'
  get 'static_pages/html_for_ui'
  get 'static_pages/line'
  get 'static_pages/log'
  get 'static_pages/log_old'
  get 'static_pages/report'
  get 'static_pages/rise_shine'
  get 'static_pages/sc2tc'
  get 'static_pages/scope_selector'

  get 'static_pages/search_index'
  get 'static_pages/search_all_in_one'
  get 'static_pages/search_extended'
  get 'static_pages/search_facet'
  get 'static_pages/search_filter'
  get 'static_pages/search_kwic'
  get 'static_pages/search_notes'
  get 'static_pages/search_sc'
  get 'static_pages/search_similar'
  get 'static_pages/search_synonym'
  get 'static_pages/search_title'
  get 'static_pages/search_toc'
  get 'static_pages/search_vars'
  get 'static_pages/search'

  get 'static_pages/sphinx_all_in_one'
  get 'static_pages/sphinx_extended'
  get 'static_pages/sphinx_facet'
  get 'static_pages/sphinx_filter'
  get 'static_pages/sphinx_notes'
  get 'static_pages/sphinx_sc'
  get 'static_pages/sphinx_synonym'
  get 'static_pages/sphinx_title'
  get 'static_pages/sphinx_vars'
  get 'static_pages/sphinx'
  get 'static_pages/time'
  get 'static_pages/toc'
  get 'static_pages/word_count'
  get 'static_pages/word_seg'
  get 'static_pages/works'
  get 'static_pages/work_index'
  get 'static_pages/work'
  get 'textref/meta'
  get 'textref/data'
  match 'toc', to: 'toc_node#index', via: [:get, :post]

  match 'word_seg2', to: 'word_seg#run', via: [:get, :post]
  match 'word_seg', to: 'word_seg#index', via: [:get, :post]

  match 'works/toc', via: [:get, :post]
  match 'work/:work_id/juan/:juan/edition/:ed', to: 'juans#edition', via: [:get, :post]
  match 'works/word_count', via: [:get, :post]
  match 'works', to: 'works#index', via: [:get, :post]

  #match ':controller', action: 'index', via: [:get, :post]
end

app/controllers/report_controller.rb
require 'will_paginate/array'
class ReportController < ApplicationController
  def daily
    @visits = Visit.group(:accessed_at).order(accessed_at: :desc).sum(:count)
    a = @visits.values
    @max = a.max
    @sum = a.sum(0)
    @avg = @sum / a.size
    
    @visit_keys = @visits.keys.paginate(page: params[:page])

    respond_to do |format|
      format.html { render }
      format.csv { daily_csv }
    end
  end

  def url
    @d1 = h2d(params[:d1])
    @d2 = h2d(params[:d2])
    @visits = Visit.where(:accessed_at => @d1..@d2).group(:url, :referer)
    h = @visits.sum(:count)
    @visits = h.sort_by { |k,v| -v }
    @total = @visits.sum(0) { |x| x[1] }

    respond_to do |format|
      format.html
      format.csv { url_csv }
    end
  end

  def referer
    @d1 = h2d(params[:d1])
    @d2 = h2d(params[:d2])
    @visits = Visit.where(:accessed_at => @d1..@d2).group(:referer)
    h = @visits.sum(:count)
    @visits = h.sort_by { |k,v| -v }
    @total = @visits.sum(0) { |x| x[1] }

    respond_to do |format|
      format.html
      format.csv { referer_csv }
    end
  end

  def total
    fn = Rails.root.join('data', 'stat-all.json')
    render json: JSON.load_file(fn)
  end

  private

  def h2d(h)
    return Date.today if h.nil?
    return Date.parse(h) if h.kind_of?(String)
    Date.new(h['year'].to_i, h['month'].to_i, h['day'].to_i)
  end

  def daily_csv
    headers = %w[date count]
    data = CSV.generate(headers: true) do |csv|
      csv << headers    
      @visits.each do |k, v|
        csv << [k, v]
      end
    end
    send_data data, filename: "cbdata-daily-#{Date.today}.csv"
  end

  def url_csv
    headers = %w[url referer count]
    data = CSV.generate(headers: true) do |csv|
      csv << headers    
      @visits.each do |a|
        csv << [a[0][0], a[0][1], a[1]]
      end
    end
    send_data data, filename: "cbdata-url-#{Date.today}.csv"
  end

  def referer_csv
    headers = %w[referer count]
    data = CSV.generate(headers: true) do |csv|
      csv << headers    
      @visits.each do |a|
        csv << [a[0], a[1]]
      end
    end
    send_data data, filename: "cbdata-referer-#{Date.today}.csv"
  end
end

app/views/report/_datepicker.haml
.row.justify-content-center
  .col-auto
    %p
      = form_with(url: url, method: :get, local: true) do |f|
        起始日期：
        = f.text_field :d1
        結束日期：
        = f.text_field :d2
        = f.submit "送出"

app/views/report/daily.haml
.row.justify-content-center
  .col-auto
    %h1 API 存取統計表 Group by Date
    %p.text-center= link_to 'Export CSV', report_daily_path(format: "csv")
    %p
      資料庫總筆數： 
      =number_with_delimiter(Visit.count)
      %br
      存取總數：
      =number_with_delimiter(@sum)
      %br
      單日最高：
      =number_with_delimiter(@max)
      %br
      單日平均：
      =number_with_delimiter(@avg)
.row.justify-content-center
  .col-auto
    = will_paginate @visit_keys, renderer: WillPaginate::ActionView::BootstrapLinkRenderer
    %table.table-striped
      %tr
        %th Date
        %th Count
      - @visit_keys.each do |k|
        - v = @visits[k]
        %tr
          %td{ style: 'padding-right: 2em' }= k
          %td.text-right= number_with_delimiter(v)

app/views/report/index.haml
%h1 統計報表
%h2 全集成 統計數字

%p= link_to_url '/report/total'

%p CBETA 收錄內容可分為兩大類：
%ul
  %li textbody (本文)
  %li non-textbody (非本文)： 例如 ZWa001 (緣起)、ZWa002 (卷首語)、ZWa003 (目錄)

%p 回傳資料
%ul
  %li
    total (全部)
    %ul
      %li works_all (典籍部數，含 non-textbody)
      %li works_main (典籍部數，不含 non-textbody)
      %li juans_all (典籍卷數，含 non-textbody)
      %li juans_main (典籍卷數，不含 non-textbody)
      %li cjk_chars_all (CJK 字元數，含 non-textbody)
      %li cjk_chars_main (CJK 字元數，不含 non-textbody)
      %li en_words_all (英文、梵巴轉寫 word 數量，含 non-textbody)
      %li en_words_main (英文、梵巴轉寫 word 數量，不含 non-textbody)
      %li 新標卷數
      %li 新標部數
      %li CBETA_新標卷數 (原書無新標，由 CBETA 執行製作)
      %li CBETA_新標部數 (原書無新標，由 CBETA 執行製作)
  %li 
    by_canon (分藏別)
    %ul
      %li 欄位同上

app/views/report/referer.haml
.row.justify-content-center
  .col-auto
    %h1 API 存取統計表 Group by Referer

= render partial: "datepicker" , locals: { url: report_referer_path }

.row.justify-content-center
  .col-auto
    %p
      = "日期範圍：#{@d1} ~ #{@d2}"
      = surround '(', ')' do
        =link_to 'Export CSV', report_referer_path(format: 'csv', d1: @d1, d2: @d2)
    %p
      Total: 
      = number_with_delimiter(@total)
    %table.table-striped.table-bordered
      %tr
        %th Referer
        %th Count
      - total = 0
      - @visits.each do |a|
        - total += a[1]
        %tr
          %td.fit= a[0]
          %td.text-right.fit= number_with_delimiter(a[1])
:javascript
  $( function() {
    report_init_datepicker()
  } );

app/views/report/url.haml
.row.justify-content-center
  .col-auto
    %h1 API 存取統計表 Group by URL

= render partial: "datepicker" , locals: { url: report_url_path }

.row.justify-content-center
  .col-auto
    %p
      = "日期範圍：#{@d1} ~ #{@d2}"
      = surround '(', ')' do
        =link_to 'Export CSV', report_url_path(format: 'csv', d1: @d1, d2: @d2)
    %p
      Total: 
      = number_with_delimiter(@total)
    %table.table-striped.table-bordered
      %tr
        %th URL
        %th Referer
        %th Count
      - total = 0
      - @visits.each do |a|
        - total += a[1]
        %tr
          %td.fit= a[0][0]
          %td.fit= a[0][1]
          %td.text-right.fit= number_with_delimiter(a[1])
:javascript
  $( function() {
    report_init_datepicker()
  } );